CREATE TABLE Usuario (
    CPF CHAR(11) NOT NULL PRIMARY KEY,
    Nome VARCHAR(255) NOT NULL,
    Telefone CHAR(11) NOT NULL,
    Formacao VARCHAR(255) NOT NULL
);

CREATE TABLE Empresa (
    CNPJ CHAR(14) NOT NULL PRIMARY KEY,
    Nome VARCHAR(255) NOT NULL,
    Telefone CHAR(11) NOT NULL,
    Ramo VARCHAR(255) NOT NULL
);

CREATE TABLE Vaga (
    ID UUID NOT NULL PRIMARY KEY,
    Nome VARCHAR(255) NOT NULL,
    Cargo VARCHAR(255) NOT NULL,
    Contato VARCHAR(255) NOT NULL,
    Formacao VARCHAR(255) NOT NULL,
    CNPJ CHAR(14) NOT NULL,
    Descricao TEXT NOT NULL,
    Aprovado BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (CNPJ) REFERENCES Empresa(CNPJ)
);

CREATE TABLE Inscricao (
    ID UUID NOT NULL PRIMARY KEY,
    CPF CHAR(11) NOT NULL,
    VagaID UUID NOT NULL,
    DataInscricao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (CPF) REFERENCES Usuario(CPF),
    FOREIGN KEY (VagaID) REFERENCES Vaga(ID)
);


